In [1]:
import numpy as np

# Quiz: Neural Network Basics

<font size="2" color="red"><b> PREGUNTA 1 </b></font>

¿Qué calcula una neurona?

- Una neurona calcula una función lineal ($z = Wx + b$) seguida de una función de activación
- Una neurona calcula una función de activación seguida de una función lineal ($z = Wx + b$)
- Una neurona calcula una función g que escala la entrada x linealmente ($Wx + b$)
- Una neurona calcula la media de todas las características antes de aplicar la salida a una función de activación

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: Una neurona calcula una función lineal ($z = Wx + b$) seguida de una función de activación.
    
Correcto, generalmente decimos que la salida de una neurona es a = g($Wx + b$) donde g es la función de activación (sigmoide, tanh, ReLU, ...).

<font size="2" color="red"><b> PREGUNTA 2 </b></font>

¿Cuál de ellas es la "Pérdida Logística"?

- $\mathcal{L}^{(i)}(\hat{y}^{(i)}, y^{(i)}) = -( y^{(i)}log(\hat{y}^{(i)}) + (1- y^{(i)})\log(1-\hat{y}^{(i)})$
- $\mathcal{L}^{(i)}(\hat{y}^{(i)}, y^{(i)}) = \mid y^{(i)} - \hat{y}^{(i)} \mid^{2}$
- $\mathcal{L}^{(i)}(\hat{y}^{(i)}, y^{(i)}) = max(0, y^{(i)} - \hat{y}^{(i)})$
- $\mathcal{L}^{(i)}(\hat{y}^{(i)}, y^{(i)}) = \mid y^{(i)} - \hat{y}^{(i)} \mid$

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: $\mathcal{L}^{(i)}(\hat{y}^{(i)}, y^{(i)}) = -( y^{(i)}log(\hat{y}^{(i)}) + (1- y^{(i)})\log(1-\hat{y}^{(i)})$.

#### <font size="2" color="red"><b> PREGUNTA 3 </b></font>

Supongamos que img es un array (32,32,3), que representa una imagen de 32x32 con 3 canales de color rojo, verde y azul. ¿Cómo se transforma en un vector columna?

- `x = img.reshape((1,32*32,*3))`
- `x = img.reshape((3,32*32))`
- `x = img.reshape((32*32*3,1))`
- `x = img.reshape((32*32,3))`

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: x = img.reshape((32*32*3,1)).

In [13]:
# Definimos img
img = np.random.rand(3,5,5)
print('MATRIZ ORIGINAL\n', img)
# Reformamos según las opciones del ejercicio
#x = img.reshape((1,5*5,*3))    #Da error
#x = img.reshape((3,5*5))       #Reforma 3 matrices de 1x25
#x = img.reshape((5*5*3,1))     #Reforma a vector columna
#x = img.reshape((5*5,3))       #Reforma 25 matrices de 1x3
print('\nMATRIZ REFORMADA\n', x)

MATRIZ ORIGINAL
 [[[0.17702205 0.79465128 0.13076783 0.85263709 0.6827936 ]
  [0.41937077 0.05531012 0.67371678 0.33112755 0.04329919]
  [0.34249333 0.12876406 0.65082568 0.29653049 0.70995969]
  [0.40226313 0.21332217 0.57006539 0.42005369 0.44440336]
  [0.50796195 0.75296741 0.53899605 0.961599   0.95497066]]

 [[0.845249   0.79066947 0.35988893 0.32311319 0.79589107]
  [0.90025573 0.18430013 0.10666706 0.56134678 0.2812283 ]
  [0.48872698 0.12570217 0.7647622  0.17508552 0.48598573]
  [0.75204917 0.39096835 0.57729356 0.88280575 0.26429217]
  [0.40287177 0.07184148 0.020895   0.54252273 0.96181506]]

 [[0.33116203 0.45398608 0.22693185 0.30996073 0.27554085]
  [0.24140769 0.02022224 0.71092491 0.32899773 0.84792073]
  [0.92062986 0.2330728  0.96315757 0.91455664 0.40608264]
  [0.84475065 0.05808597 0.87686383 0.16200634 0.94524903]
  [0.69278628 0.49595855 0.4671054  0.29641422 0.81544736]]]

MATRIZ REFORMADA
 [[0.64009463 0.54268284 0.54430927]
 [0.78199549 0.19523862 0.91747291]
 

<font size="2" color="red"><b> PREGUNTA 4 </b></font>

Considera las dos siguientes matrices aleatorias aa y bb:

```python
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
```

¿Cuál será la forma de cc?

- `c.shape = (2, 3)`
- `c.shape = (3, 2)`
- `c.shape = (2, 1)`
- El cálculo no puede realizarse porque los tamaños no coinciden. ¡Va a ser "Error"!

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: `c.shape = (2, 3)`.
    
Correcto, Esto es el broadcasting. b (vector de columnas) se copia 3 veces para que se pueda sumar a cada columna de a.

In [17]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print('LA MATRIZ ES: \n', c)
print('\nLA FORMA ES: \n', c.shape)

LA MATRIZ ES: 
 [[-1.86478647 -1.60989898 -1.59048293]
 [ 0.52122694  0.04771246  1.34663855]]

LA FORMA ES: 
 (2, 3)


<font size="2" color="red"><b> PREGUNTA 5 </b></font>

Considere las dos siguientes matrices aleatorias aa y bb:

```python
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
```

¿Cuál será la forma de cc?

- `c.shape = (3,3)`
- `c.shape = (4,3)`
- `c.shape = (4,2)`
- El cálculo no puede realizarse porque los tamaños no coinciden. ¡Va a ser "Error"!

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: El cálculo no puede realizarse porque los tamaños no coinciden. ¡Va a ser "Error"!.
    
Correcto, Efectivamente. En numpy el operador "*" indica la multiplicación por elementos. Es diferente de "`np.dot()`". Si intentaras "`c = np.dot(a,b)`" obtendrías `c.shape = (4, 2)`.

In [18]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print('LA MATRIZ ES: \n', c)
print('\nLA FORMA ES: \n', c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

<font size="2" color="red"><b> PREGUNTA 6 </b></font>

Supón que tienes $n_x$ características de entrada por ejemplo. Recordemos que $X = [x^{(1)} x^{(2)} ... x^{(m)}]$. ¿Cuál es la dimensión de $X$? 

- $(1,m)$
- $(m,n_x)$
- $(n_x, m)$
- $(m,1)$

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: $(n_x, m)$.

<font size="2" color="red"><b> PREGUNTA 7 </b></font>

Recuerda que `np.dot(a,b)` realiza una multiplicación matricial sobre $a$ y $b$, mientras que `a*b` realiza una multiplicación por elementos.

Consideremos las dos siguientes matrices aleatorias $a$ y $b$:

```python
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
```

¿Cuál es la forma de cc?

- `c.shape = (12288, 45)`
- `c.shape = (12288, 150)`
- El cálculo no puede realizarse porque los tamaños no coinciden. Se producirá un "error".
- `c.shape = (150,150)`

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: `c.shape = (12288, 45)`.
    
Correcto, recuerda que un `np.dot(a, b)` tiene forma (número de filas de $a$, número de columnas de $b$). Los tamaños coinciden porque: "número de columnas de a = 150 = número de filas de b".

In [19]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print('\nLA FORMA ES: \n', c.shape)


LA FORMA ES: 
 (12288, 45)


<font size="2" color="red"><b> PREGUNTA 8 </b></font>

Considere el siguiente fragmento de código:

```python
# a.shape = (3,4)a.shape=(3,4)
# b.shape = (4,1)b.shape=(4,1)

para i en rango(3):
     for j in range(4):
          c[i][j] = a[i][j] + b[j]c[i][j]=a[i][j]+b[j] 
```

¿Cómo se vectoriza esto?

- c = a.T + b.T
- c = a + b.T
- c = a + b
- c = a.T + b

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: c = a + b.T.
   

<font size="2" color="red"><b> PREGUNTA 9 </b></font>

¿Qué calcula una neurona?

Considera el siguiente código:

```python
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
```

¿Qué será $c$? (Si no estás seguro, no dudes en ejecutar esto en python para averiguarlo).

- Se producirá un error ya que no se puede utilizar "*" para operar en estas dos matrices. En su lugar, debe utilizar `np.dot(a,b)`.
- Esto invocará la difusión, por lo que b se copia tres veces para convertirse en (3,3), y * es un producto elemento a elemento por lo que `c.shape` será (3, 3).
- Esto multiplicará una matriz 3x3 a con un vector 3x1, resultando así un vector 3x1. Es decir, `c.shape = (3,1)`. 
- Esto invocará la emisión, por lo que b se copia tres veces para convertirse en (3, 3), y * invoca una operación de multiplicación matricial de dos matrices de 3x3 por lo que `c.shape` será (3, 3)


<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: Esto invocará la difusión, por lo que b se copia tres veces para convertirse en $(3,3)$, y * es un producto elemento a elemento por lo que `c.shape` será $(3, 3)$.

In [20]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[-1.08523426,  0.7630263 ,  1.00381342],
       [ 0.04198414,  4.95701368,  2.73104859],
       [-0.6255174 ,  0.04022646,  0.37150006]])

<font size="2" color="red"><b> PREGUNTA 10 </b></font>

Considere el siguiente gráfico de cálculo.

<figure>
 <img align="center", src="./EjercicioQuiz.jpg", style="width:60%;" >
</figure>


¿Cuál es la salida J?

- $J = (a - 1) * (b + c)$
- $J = (c - 1)*(b + a)$
- $J = a*b + b*c + a*c$
- $J = (b - 1) * (c + a)$

<details>
   <summary><font size="2" color="darkblue"><b> Click para la respuesta</b></font></summary>

Respuesta: $J = (a - 1) * (b + c)$

J = u + v - w 
  = a*b + a*c - (b + c) 
  = a * (b + c) - (b + c) 
  = (a - 1) * (b + c)
